service: authorization-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    raaz1017: ${env.raaz1017}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer