service: import-service
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  httpApi:
    cors: true
  environment:
    SQS_URL: ${env.SQS_URL}
    SQS_ARN: ${env.SQS_ARN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::product-shop-rs"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "arn:aws:s3:::product-shop-rs/*"
        - Effect: "Allow"
          Action: "sqs:*"
          Resource: "arn:aws:sqs:eu-west-1:248058432125:catalogItemsQueue"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: /import
          method: get
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: product-shop-rs
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true